### PR TITLE
Delete add dates script

### PR DESCRIPTION
**Pull request by carvil**
We are hiding the dates in the prototype as they are confusing. We don't
need to have this script anymore.

### CODE REVIEW

**Comment by carolinegreen** [comment]
👍 I thought it was already gone!

**Comment by alextea** [comment]
Looks good to me. Should we delete the css too, or wait for the next input?

**Comment by carolinegreen** [comment]
@alextea Yeah good point, should probably go too.

**Comment by carvil** [comment]
@alext good point, will delete the CSS rule in another PR

**Pull request merged**
