### PR TITLE
Javascript lint

### PR DESCRIPTION
**Pull request by rubenarakelyan**
This commit adds a JavaScript linter and corrects some linting errors.

### CODE REVIEW

**Comment by carolinegreen** [comment]
I'd really prefer this wasn't added as a ruby gem, when it's a node application.

**Comment by MatMoore** [comment]
@carolinegreen I think the gem is just a wrapper so you can run it from the rake task. Not sure if we have a preference for how to run these things: at the moment some things are scripts in `bin`, some are run by `rake` and some via `npm`.

It's not ideal but for a prototype I don't mind so much. Would you prefer to keep the javascript stuff handled by the node toolchain?

**Comment by carolinegreen** [comment]
@MatMoore I know what it is, but it's pretty bizarre to run a rake task in a node application to lint javascript.  I would prefer we use npm.  It is a prototype, but if code is being refactored in other pull requests, there is some kind of standard being applied here.  Even if that wasn't happening, it's still weird to lint using something that's really not meant for this situation.

**Comment by carolinegreen** [comment]
Linting is a good idea, but it would be better to use node.  I'm going to close this, so it doesn't get merged.

**Pull request closed without merging**
